apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xray-routing-panel-shared
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
