apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: xray-routing-panel

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - storage.yaml
  - xray-reloader-configmap.yaml
  - deployment.yaml
  - service.yaml
  - cronjob-backup.yaml
