import base64
import json
from urllib.parse import quote, urlencode

from .config import XRAY_CLIENT_CONFIG_PATH
from .helpers import external_url_for, normalize_subscription_name, yaml_quote


def parse_xray_client_profile():
    if not XRAY_CLIENT_CONFIG_PATH.is_file():
        return None, f"未找到 Xray 客户端配置：{XRAY_CLIENT_CONFIG_PATH}"

    try:
        payload = json.loads(XRAY_CLIENT_CONFIG_PATH.read_text(encoding="utf-8"))
        outbounds = payload.get("outbounds", [])
        if not isinstance(outbounds, list) or not outbounds:
            raise ValueError("outbounds 为空")
        outbound = next((item for item in outbounds if item.get("protocol") == "vless"), outbounds[0])
        vnext = outbound["settings"]["vnext"][0]
        user = vnext["users"][0]
        reality = outbound["streamSettings"]["realitySettings"]
        profile = {
            "server": str(vnext["address"]).strip(),
            "uuid": str(user["id"]).strip(),
            "flow": str(user.get("flow", "")).strip(),
            "server_name": str(reality["serverName"]).strip(),
            "public_key": str(reality["publicKey"]).strip(),
            "short_id": str(reality["shortId"]).strip(),
            "fingerprint": str(reality.get("fingerprint", "chrome")).strip() or "chrome",
        }
    except (KeyError, IndexError, TypeError, ValueError, json.JSONDecodeError) as exc:
        return None, f"Xray 客户端配置解析失败：{exc}"

    missing = [key for key, value in profile.items() if not value]
    if missing:
        return None, f"Xray 客户端配置缺少字段：{', '.join(missing)}"
    return profile, ""


def build_vless_share_link(profile, listen_port, note):
    params = urlencode(
        {
            "encryption": "none",
            "flow": profile["flow"],
            "security": "reality",
            "sni": profile["server_name"],
            "fp": profile["fingerprint"],
            "pbk": profile["public_key"],
            "sid": profile["short_id"],
            "type": "tcp",
            "headerType": "none",
        }
    )
    tag = quote(normalize_subscription_name(note, listen_port), safe="")
    return f"vless://{profile['uuid']}@{profile['server']}:{int(listen_port)}?{params}#{tag}"


def build_v2ray_subscription_content(profile, listen_port, note):
    share_link = build_vless_share_link(profile, listen_port, note)
    return base64.b64encode(f"{share_link}\n".encode("utf-8")).decode("ascii")


def build_clash_subscription_content(profile, listen_port, note):
    proxy_name = normalize_subscription_name(note, listen_port)
    lines = [
        "port: 7890",
        "socks-port: 7891",
        "allow-lan: true",
        "mode: rule",
        "log-level: info",
        "ipv6: true",
        "",
        "dns:",
        "  enable: true",
        "  listen: 0.0.0.0:1053",
        "  ipv6: true",
        "  enhanced-mode: fake-ip",
        "  nameserver:",
        "    - https://dns.google/dns-query",
        "    - https://1.1.1.1/dns-query",
        "",
        "proxies:",
        f"  - name: {yaml_quote(proxy_name)}",
        "    type: vless",
        f"    server: {yaml_quote(profile['server'])}",
        f"    port: {int(listen_port)}",
        f"    uuid: {yaml_quote(profile['uuid'])}",
        "    udp: true",
        "    tls: true",
        "    network: tcp",
        f"    servername: {yaml_quote(profile['server_name'])}",
        f"    flow: {yaml_quote(profile['flow'])}",
        "    reality-opts:",
        f"      public-key: {yaml_quote(profile['public_key'])}",
        f"      short-id: {yaml_quote(profile['short_id'])}",
        f"    client-fingerprint: {yaml_quote(profile['fingerprint'])}",
        "",
        "proxy-groups:",
        "  - name: PROXY",
        "    type: select",
        "    proxies:",
        f"      - {yaml_quote(proxy_name)}",
        "      - DIRECT",
        "",
        "  - name: AUTO",
        "    type: url-test",
        "    url: http://www.gstatic.com/generate_204",
        "    interval: 300",
        "    proxies:",
        f"      - {yaml_quote(proxy_name)}",
        "",
        "rule-providers:",
        "  BanAD:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/BanAD.yaml",
        "    path: ./ruleset/BanAD.yaml",
        "    interval: 86400",
        "",
        "  BanEasyList:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/BanEasyList.yaml",
        "    path: ./ruleset/BanEasyList.yaml",
        "    interval: 86400",
        "",
        "  BanEasyListChina:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/BanEasyListChina.yaml",
        "    path: ./ruleset/BanEasyListChina.yaml",
        "    interval: 86400",
        "",
        "  BanEasyPrivacy:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/BanEasyPrivacy.yaml",
        "    path: ./ruleset/BanEasyPrivacy.yaml",
        "    interval: 86400",
        "",
        "  BanProgramAD:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/BanProgramAD.yaml",
        "    path: ./ruleset/BanProgramAD.yaml",
        "    interval: 86400",
        "",
        "  Download:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Download.yaml",
        "    path: ./ruleset/Download.yaml",
        "    interval: 86400",
        "",
        "  LocalAreaNetwork:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/LocalAreaNetwork.yaml",
        "    path: ./ruleset/LocalAreaNetwork.yaml",
        "    interval: 86400",
        "",
        "  UnBan:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/UnBan.yaml",
        "    path: ./ruleset/UnBan.yaml",
        "    interval: 86400",
        "",
        "  ChinaDomain:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/ChinaDomain.yaml",
        "    path: ./ruleset/ChinaDomain.yaml",
        "    interval: 86400",
        "",
        "  ChinaCompanyIp:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/ChinaCompanyIp.yaml",
        "    path: ./ruleset/ChinaCompanyIp.yaml",
        "    interval: 86400",
        "",
        "  ChinaIp:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/ChinaIp.yaml",
        "    path: ./ruleset/ChinaIp.yaml",
        "    interval: 86400",
        "",
        "  ChinaMedia:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/ChinaMedia.yaml",
        "    path: ./ruleset/ChinaMedia.yaml",
        "    interval: 86400",
        "",
        "  ProxyGFWlist:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/ProxyGFWlist.yaml",
        "    path: ./ruleset/ProxyGFWlist.yaml",
        "    interval: 86400",
        "",
        "  ProxyMedia:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/ProxyMedia.yaml",
        "    path: ./ruleset/ProxyMedia.yaml",
        "    interval: 86400",
        "",
        "  Apple:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/Apple.yaml",
        "    path: ./ruleset/Apple.yaml",
        "    interval: 86400",
        "",
        "  Bilibili:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/Bilibili.yaml",
        "    path: ./ruleset/Bilibili.yaml",
        "    interval: 86400",
        "",
        "  BilibiliHMT:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/BilibiliHMT.yaml",
        "    path: ./ruleset/BilibiliHMT.yaml",
        "    interval: 86400",
        "",
        "  Google:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/Google.yaml",
        "    path: ./ruleset/Google.yaml",
        "    interval: 86400",
        "",
        "  GoogleCN:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/GoogleCN.yaml",
        "    path: ./ruleset/GoogleCN.yaml",
        "    interval: 86400",
        "",
        "  GoogleFCM:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/GoogleFCM.yaml",
        "    path: ./ruleset/GoogleFCM.yaml",
        "    interval: 86400",
        "",
        "  Microsoft:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/Microsoft.yaml",
        "    path: ./ruleset/Microsoft.yaml",
        "    interval: 86400",
        "",
        "  NetEaseMusic:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/NetEaseMusic.yaml",
        "    path: ./ruleset/NetEaseMusic.yaml",
        "    interval: 86400",
        "",
        "  Netflix:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/Netflix.yaml",
        "    path: ./ruleset/Netflix.yaml",
        "    interval: 86400",
        "",
        "  OneDrive:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/OneDrive.yaml",
        "    path: ./ruleset/OneDrive.yaml",
        "    interval: 86400",
        "",
        "  Spotify:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/Spotify.yaml",
        "    path: ./ruleset/Spotify.yaml",
        "    interval: 86400",
        "",
        "  Steam:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/Steam.yaml",
        "    path: ./ruleset/Steam.yaml",
        "    interval: 86400",
        "",
        "  SteamCN:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/SteamCN.yaml",
        "    path: ./ruleset/SteamCN.yaml",
        "    interval: 86400",
        "",
        "  Telegram:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/Telegram.yaml",
        "    path: ./ruleset/Telegram.yaml",
        "    interval: 86400",
        "",
        "  YouTube:",
        "    type: http",
        "    behavior: classical",
        "    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/YouTube.yaml",
        "    path: ./ruleset/YouTube.yaml",
        "    interval: 86400",
        "",
        "rules:",
        "  - RULE-SET,Download,DIRECT",
        "  - RULE-SET,LocalAreaNetwork,DIRECT",
        "  - RULE-SET,BanAD,REJECT",
        "  - RULE-SET,BanEasyList,REJECT",
        "  - RULE-SET,BanEasyListChina,REJECT",
        "  - RULE-SET,BanEasyPrivacy,REJECT",
        "  - RULE-SET,BanProgramAD,REJECT",
        "  - DOMAIN-SUFFIX,cn,DIRECT",
        "  - RULE-SET,ChinaCompanyIp,DIRECT",
        "  - RULE-SET,ChinaDomain,DIRECT",
        "  - RULE-SET,ChinaIp,DIRECT",
        "  - RULE-SET,SteamCN,DIRECT",
        "  - RULE-SET,ProxyGFWlist,PROXY",
        "  - RULE-SET,Telegram,PROXY",
        "  - RULE-SET,UnBan,DIRECT",
        "  - RULE-SET,ChinaMedia,DIRECT",
        "  - RULE-SET,ProxyMedia,PROXY",
        "  - RULE-SET,Bilibili,DIRECT",
        "  - RULE-SET,BilibiliHMT,PROXY",
        "  - RULE-SET,NetEaseMusic,DIRECT",
        "  - RULE-SET,GoogleCN,DIRECT",
        "  - RULE-SET,GoogleFCM,PROXY",
        "  - RULE-SET,Google,PROXY",
        "  - RULE-SET,Apple,PROXY",
        "  - RULE-SET,Microsoft,PROXY",
        "  - RULE-SET,OneDrive,PROXY",
        "  - RULE-SET,Netflix,PROXY",
        "  - RULE-SET,Spotify,PROXY",
        "  - RULE-SET,Steam,PROXY",
        "  - RULE-SET,YouTube,PROXY",
        "  - GEOIP,CN,DIRECT",
        "  - MATCH,PROXY",
        "",
    ]
    return "\n".join(lines)


def build_port_access_payload(port, subscription_profile):
    payload = {
        "tenant_panel_url": external_url_for("tenant_panel", tenant_token=port["tenant_token"]),
        "tenant_login_url": external_url_for("tenant_login", tenant_token=port["tenant_token"]),
        "tenant_username": str(port.get("tenant_username") or ""),
        "tenant_password": str(port.get("tenant_password") or ""),
        "tenant_subscription_default_url": "",
        "tenant_subscription_clash_url": "",
        "tenant_subscription_v2ray_url": "",
        "share_link": "",
    }
    if subscription_profile is None:
        return payload

    payload["tenant_subscription_default_url"] = external_url_for(
        "tenant_subscription_default",
        subscription_token=port["subscription_token"],
    )
    payload["tenant_subscription_clash_url"] = external_url_for(
        "tenant_subscription_clash",
        subscription_token=port["subscription_token"],
    )
    payload["tenant_subscription_v2ray_url"] = external_url_for(
        "tenant_subscription_v2ray",
        subscription_token=port["subscription_token"],
    )
    payload["share_link"] = build_vless_share_link(subscription_profile, port["listen_port"], port["note"])
    return payload
