#!/bin/sh
set -eu

: "${DB_PATH:=/data/panel.db}"
: "${DB_BACKUP_DIR:=/backups}"
: "${DB_BACKUP_KEEP_DAYS:=7}"
: "${DB_BACKUP_PREFIX:=xray-routing-panel}"
: "${DB_BACKUP_BUNDLE_ENABLED:=1}"
: "${DB_BACKUP_BUNDLE_DIR:=/backups}"
: "${DB_BACKUP_BUNDLE_KEEP_DAYS:=$DB_BACKUP_KEEP_DAYS}"
: "${DB_BACKUP_BUNDLE_PREFIX:=$DB_BACKUP_PREFIX}"
: "${DB_BACKUP_EXTRA_PATHS:=}"
: "${DB_BACKUP_SSH_COLLECTION_ENABLED:=0}"
: "${DB_BACKUP_SSH_COLLECTION_REQUIRED:=0}"
: "${DB_BACKUP_SSH_KEY_PATH:=/run/secrets/fleet_ssh_key}"
: "${DB_BACKUP_SSH_OPTIONS:=}"
: "${DB_BACKUP_SSH_TIMEOUT_SECONDS:=20}"
: "${DB_BACKUP_SSH_MAX_FILE_BYTES:=5242880}"
: "${DB_BACKUP_DATAPLANE_SSH_TARGET:=}"
: "${DB_BACKUP_DATAPLANE_SSH_PORT:=22}"
: "${DB_BACKUP_DATAPLANE_KNOWN_HOSTS:=/root/.ssh/known_hosts}"
: "${DB_BACKUP_DATAPLANE_SSH_OPTIONS:=}"
: "${DB_BACKUP_DATAPLANE_CONFIG_PATH:=}"
: "${DB_BACKUP_DATAPLANE_REMOTE_PATHS:=/root/xray-routing-panel/app/xray/runtime/config.json,/root/xray-routing-panel/app/xray/.env}"
: "${DB_BACKUP_AI_NODE_SSH_TARGET:=}"
: "${DB_BACKUP_AI_NODE_SSH_PORT:=27160}"
: "${DB_BACKUP_AI_NODE_KNOWN_HOSTS:=/root/.ssh/known_hosts_ai}"
: "${DB_BACKUP_AI_NODE_SSH_OPTIONS:=}"
: "${DB_BACKUP_AI_NODE_CONFIG_PATH:=}"
: "${DB_BACKUP_AI_NODE_REMOTE_PATHS:=}"
: "${DB_BACKUP_CRON_SCHEDULE:=0 3 * * *}"
: "${DB_BACKUP_R2_ENABLED:=0}"
: "${DB_BACKUP_R2_ENDPOINT:=}"
: "${DB_BACKUP_R2_BUCKET:=}"
: "${DB_BACKUP_R2_ACCESS_KEY_ID:=}"
: "${DB_BACKUP_R2_SECRET_ACCESS_KEY:=}"
: "${DB_BACKUP_R2_REGION:=auto}"
: "${DB_BACKUP_R2_PREFIX:=xray-routing-panel}"
: "${DB_BACKUP_R2_RECORD_PATH:=/backups/r2-upload-record.json}"
: "${DB_BACKUP_ENCRYPTION_PASSWORD:=}"

ENV_FILE=/etc/xray-routing-panel-db-backup.env
CRON_FILE=/etc/cron.d/xray-routing-panel-db-backup

write_env() {
  key=$1
  value=$2
  escaped=$(printf "%s" "$value" | sed "s/'/'\"'\"'/g")
  printf "export %s='%s'\n" "$key" "$escaped" >> "$ENV_FILE"
}

mkdir -p /etc/cron.d "$DB_BACKUP_DIR" /var/log

: >"$ENV_FILE"
write_env DB_PATH "$DB_PATH"
write_env DB_BACKUP_DIR "$DB_BACKUP_DIR"
write_env DB_BACKUP_KEEP_DAYS "$DB_BACKUP_KEEP_DAYS"
write_env DB_BACKUP_PREFIX "$DB_BACKUP_PREFIX"
write_env DB_BACKUP_BUNDLE_ENABLED "$DB_BACKUP_BUNDLE_ENABLED"
write_env DB_BACKUP_BUNDLE_DIR "$DB_BACKUP_BUNDLE_DIR"
write_env DB_BACKUP_BUNDLE_KEEP_DAYS "$DB_BACKUP_BUNDLE_KEEP_DAYS"
write_env DB_BACKUP_BUNDLE_PREFIX "$DB_BACKUP_BUNDLE_PREFIX"
write_env DB_BACKUP_EXTRA_PATHS "$DB_BACKUP_EXTRA_PATHS"
write_env DB_BACKUP_SSH_COLLECTION_ENABLED "$DB_BACKUP_SSH_COLLECTION_ENABLED"
write_env DB_BACKUP_SSH_COLLECTION_REQUIRED "$DB_BACKUP_SSH_COLLECTION_REQUIRED"
write_env DB_BACKUP_SSH_KEY_PATH "$DB_BACKUP_SSH_KEY_PATH"
write_env DB_BACKUP_SSH_OPTIONS "$DB_BACKUP_SSH_OPTIONS"
write_env DB_BACKUP_SSH_TIMEOUT_SECONDS "$DB_BACKUP_SSH_TIMEOUT_SECONDS"
write_env DB_BACKUP_SSH_MAX_FILE_BYTES "$DB_BACKUP_SSH_MAX_FILE_BYTES"
write_env DB_BACKUP_DATAPLANE_SSH_TARGET "$DB_BACKUP_DATAPLANE_SSH_TARGET"
write_env DB_BACKUP_DATAPLANE_SSH_PORT "$DB_BACKUP_DATAPLANE_SSH_PORT"
write_env DB_BACKUP_DATAPLANE_KNOWN_HOSTS "$DB_BACKUP_DATAPLANE_KNOWN_HOSTS"
write_env DB_BACKUP_DATAPLANE_SSH_OPTIONS "$DB_BACKUP_DATAPLANE_SSH_OPTIONS"
write_env DB_BACKUP_DATAPLANE_CONFIG_PATH "$DB_BACKUP_DATAPLANE_CONFIG_PATH"
write_env DB_BACKUP_DATAPLANE_REMOTE_PATHS "$DB_BACKUP_DATAPLANE_REMOTE_PATHS"
write_env DB_BACKUP_AI_NODE_SSH_TARGET "$DB_BACKUP_AI_NODE_SSH_TARGET"
write_env DB_BACKUP_AI_NODE_SSH_PORT "$DB_BACKUP_AI_NODE_SSH_PORT"
write_env DB_BACKUP_AI_NODE_KNOWN_HOSTS "$DB_BACKUP_AI_NODE_KNOWN_HOSTS"
write_env DB_BACKUP_AI_NODE_SSH_OPTIONS "$DB_BACKUP_AI_NODE_SSH_OPTIONS"
write_env DB_BACKUP_AI_NODE_CONFIG_PATH "$DB_BACKUP_AI_NODE_CONFIG_PATH"
write_env DB_BACKUP_AI_NODE_REMOTE_PATHS "$DB_BACKUP_AI_NODE_REMOTE_PATHS"
write_env DB_BACKUP_R2_ENABLED "$DB_BACKUP_R2_ENABLED"
write_env DB_BACKUP_R2_ENDPOINT "$DB_BACKUP_R2_ENDPOINT"
write_env DB_BACKUP_R2_BUCKET "$DB_BACKUP_R2_BUCKET"
write_env DB_BACKUP_R2_ACCESS_KEY_ID "$DB_BACKUP_R2_ACCESS_KEY_ID"
write_env DB_BACKUP_R2_SECRET_ACCESS_KEY "$DB_BACKUP_R2_SECRET_ACCESS_KEY"
write_env DB_BACKUP_R2_REGION "$DB_BACKUP_R2_REGION"
write_env DB_BACKUP_R2_PREFIX "$DB_BACKUP_R2_PREFIX"
write_env DB_BACKUP_R2_RECORD_PATH "$DB_BACKUP_R2_RECORD_PATH"
write_env DB_BACKUP_ENCRYPTION_PASSWORD "$DB_BACKUP_ENCRYPTION_PASSWORD"

cat >"$CRON_FILE" <<EOF
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
$DB_BACKUP_CRON_SCHEDULE root . $ENV_FILE && python3 /app/scripts/run_db_backup_cycle.py >> /var/log/xray-routing-panel-db-backup.log 2>&1
EOF

chmod 0600 "$ENV_FILE"
chmod 0644 "$CRON_FILE"
touch /var/log/xray-routing-panel-db-backup.log

exec cron -f
